Transerve-PwC/frontend

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/search-duplicate-copy-preview.js
Attached application number to the duplicate copy preview page header
> added header in duplicate copy preview page

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-molecules-local/ActionDialog/index.js
1-checked payloads
2-Added text field in case of APRO and SA to enter amount
> added text field in employee section

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/rentHolderDetails.js
Relationship field bug fixed mortgage
> Relationship field bug fix

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/rentHolderDetails.js
duplicate-copy relationship field fix df09414
> duplicate-copy relationship field fix

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/notices.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/property-transitImages.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-molecules-local/MultipleDocuments/index.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-utils/apply.js
> Transit tab and notices tab fixed date,comm,name

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/acknowledgement.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/footer.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/notice-recovry.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/notice-violation.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-utils/apply.js
Notice gen viola&Recv flow commit
> Notice gen viola&Recv commit

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/footer.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/noticeDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/propertyDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/rentHolderDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/notice-recovry.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/notice-violation.js
1.Transit number is displayed as undefined after submission of Violation notice
2.Notice generation- violation "Enter Mandatory fields error"
3.Notice: Original Allottee name should get auto populated when generating violation notice
4.Page title for Recovery Notice  displays Add Rented property.
5.Violation comments are not auto populated while creating a violation notice.
> JIRA PCR 286,287,288,289,290

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/accountStatementDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/home.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/searchResource/rentedPropertyApplication.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/searchResource/searchResults.js
Ui changes in account statement generation
> UI changes in account statement generation

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/addressDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/home.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-molecules-local/MultipleDocuments/index.js
> PCR-297,298,302

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties-citizen/footer.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/review-property.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/reviewDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-molecules-local/MultipleDocuments/index.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-utils/apply.js
> PCR-312,313,314

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-utils/apply.js
> notice creation payload change

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties-citizen/footer.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/footer.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-molecules-local/MultipleDocuments/index.js
New PR for tasks PCR-272,303,323,324,325
> PCR-272,303,323,324,325

- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate/court-case.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate/document-details.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate/owner-details.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate/payment-details.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate/purchaser-details.js
Reverts Transerve-PwC/frontend#164
> Revert "Feature/estate search preview"

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/notice-violation.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/property-transitImages.js
PCR 346 map of null fix notices tab -- many notices has application docs as null which were creating issue
> PCR 346 map of null fix notices tab

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/acknowledgement.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/footer.js
PCR-323 Issue in success page notice create
> PCR-323 Issue in success page notice creat

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/acknowledgement.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/noticeDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/property-transitImages.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-utils/apply.js
PCR 304 and PCR 362 Commit and Acknowledgment fix
> PCR-304,362

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-molecules-local/ActionDialog/index.js
PCR 321 - Does not display Dates of sanctioning and mortgage date  for  Grant details in PM
> PCR 321 commit

- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/citizenSearchResource/searchFunctions.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/citizenSearchResource/searchResults.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/estate-branch-owner-details.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/estate-branch-search-preview.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate/preview-resource/owner-properties.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/utils/index.js
> changes in citizen search and apply

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/rentHolderDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/review-documents.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/review-property.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/noticestabNoticepreview.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-utils/apply.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-molecules/MultiDownloadCard/index.js
Commits for PCR:
392 -- Applicant details not getting auto populated  in DC and MG application on entering Transit site number
380 -- Download and print button issues
382 -- Notice preview
> PCR-392,380,382

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/acknowledgement.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/footer.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/noticeDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/rentHolderDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/review-applications-mortgage.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/review-property.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/notice-violation.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/noticestabNoticepreview.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/property-transitImages.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-utils/apply.js
**PCR-365,432,311,364,323,434 -> Commit**
============================
=======================
> PCR-365,432,311,364,323,434

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/propertyDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/rentHolderDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/transit-site-images.js
> PCR-447,411,376

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-molecules-local/MultiDownloadCardNoticePreview/index.scss
MultiDownloadCardNoticePreview scss file
4e23afa
> MultiDownloadCardNoticePreview scss file

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/addressDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/applyConfig.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/propertyDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/review-documents.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/review-property.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/notices.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/noticestabNoticepreview.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-molecules-local/MultiDownloadCardNoticePreview/index.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-molecules-local/MultipleDocuments/index.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-utils/apply.js
> PCR-474,514,506,383,488,492,505,525,509

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/noticestabNoticepreview.js
> printCont duplicate merge error commit

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/notice-violation.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/notices.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/search-preview.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-utils/apply.js
> PCR-520,542,536,535,515

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-molecules-local/ActionDialog/index.js
Validations for all fields added
> PCR- 565 grant details Fix

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/addressDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/rentHolderDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-utils/apply.js
> PCR-586,588

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-molecules-local/ActionDialog/index.js
> PCR-565 grant info bug

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/addressDetails.js
> PCR-605 fields clear bug

- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OtherCitizen_LeaseDeed.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OtherCitizen_LeaseDeed_preview.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OtherCitizen_NDC.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OtherCitizen_NDC_preview.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OtherCitizen_NOC.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OtherCitizen_NOC_preview.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OwnershipTransfer_PatnershipDeed.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OwnershipTransfer_PatnershipDeed_preview.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OwnershipTransfer_RegisteredWill.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OwnershipTransfer_RegisteredWill_preview.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OwnershipTransfer_SaleDeed.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OwnershipTransfer_UnRegisteredWill.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OwnershipTransfer_UnRegisteredWill_preview.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/applyResource/detailsStep.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/estate-branch-apply.js
> PE-96,97,98,99 forms

- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OtherCitizen_ChangeInTrade.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OtherCitizen_ChangeInTrade_preview.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OtherCitizen_LeaseholdToFreehold.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OtherCitizen_LeaseholdToFreehold_preview.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OtherCitizen_Mortgage.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OtherCitizen_Mortgage_preview.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/estate-branch-apply.js
- EstateBranch_OtherCitizen_ChangeInTrade
- EstateBranch_OtherCitizen_LeaseholdToFreehold
- EstateBranch_OtherCitizen_Mortgage
> PE-105,106,107 forms

- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OwnershipTransfer_RegisteredWill.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/citizenSearchResource/estateApplicationAccountStatementGen.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/citizenSearchResource/searchAccountStatementFunction.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/estate-search-account-statement.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate/home.js
> account stmt initiated, regWill changes

- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OwnershipTransfer_InstestateDeath.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OwnershipTransfer_InstestateDeath_preview.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OwnershipTransfer_RegisteredWill.json
form approval workflow checked for:
1. sale deed
2. intestate death
3. Reg will 
4. Un Reg will
> form approval workflow checked

- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OwnershipTransfer_FamilySettlement.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OwnershipTransfer_FamilySettlement_preview.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OwnershipTransfer_PatnershipDeed.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OwnershipTransfer_PatnershipDeed_preview.json
> PE-162 court decree form changes

- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OtherCitizenService_ScfToSco.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OtherCitizenService_ScfToSco_preview.json
> PE-177 form ScfToSco

- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_InternalServices_IssuanceOfNotice.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_InternalServices_IssuanceOfNotice_preview.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OtherCitizenService_LeaseDeed.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OtherCitizenService_LeaseholdToFreehold.json
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OtherCitizenService_ScfToSco.json
> Form changes notice,lease,scf

- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/EstateBranch_OtherCitizenService_ChangeInTrade.json
> Form changes in prefill estate-mortgageForm

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/addressDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/noticeDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/propertyDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/rentHolderDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/review-applications.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/payment.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/searchResource/rentedPropertyApplication.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-containers-local/WorkFlowContainer/index.js
> PCR-698 Validation/popup chngs in all applications

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/addressDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/noticeDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-molecules-local/MultipleDocuments/index.js
> PCR-721 Transit site images tab formatting fix

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/review-applications-mortgage.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/review-applications.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/review-documents.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/review-property.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-molecules-local/DocumentList/index.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-molecules-local/SimpleModal/index.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-molecules-local/index.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-utils/commons.js
> PCR723 - Feature/rp bugs oct132

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties-citizen/ownership-transfer.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/noticeDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-utils/apply.js
- Mobile: title name getting cropped for ownership transfer page
- DC,OT: Due amount not displayed in currency format
> PCR-725,726 bug Fixes

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/ownership-search-preview.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/search-duplicate-copy-preview.js
OT and DC search preview due amt fix format
> PCR-726 changes OCt22

- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate/searchResource/searchResultsAccountStatement.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-molecules-local/CustomTab/index.js
> PE-131 and other changes in acc. stmt

- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate/searchResource/searchResultsAccountStatement.js
> PE-338 bug

- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/citizenSearchResource/searchFunctions.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/estate-branch.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate/acknowledgementResource/applicationSuccessFooter.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate/estate-search-account-statement.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate/searchResource/estateApplicationAccountStatementGen.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate/searchResource/searchAccountStatementFunction.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-molecules-local/FeesEstimateCard/index.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-molecules-local/FeesEstimateCard/index.scss
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-molecules-local/RentSummaryCard/index.js
- **PE-346** - _Account statement: Owner name displays new owner, previous owner in search_
- **PE-347** - _Account statement: subcategory shows non localized value_
> PE-346, 347 Account statement Bugs

- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-config/screens/specs/rented-properties/applyResource/propertyDetails.js
- web/rainmaker/dev-packages/egov-rented-properties-dev/src/ui-utils/commons.js
> Feature/rp bugs nov12[PCR-777,772]

- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/_apply.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate-citizen/applyResource/review.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate/applyResource/footer.js
- web/rainmaker/dev-packages/egov-estate-dev/src/ui-config/screens/specs/estate/estate-payment.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-molecules/MultiDownloadCard/index.js
> PE-432,433,434,438,443,429 bugs commit
